# Generated by Django 3.1.7 on 2021-04-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPIapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Ope Joseph', max_length=30),
        ),
    ]
